### ISSUE TITLE
Easier access to TraitUnlock display names

### ISSUE THREAD

**Issue by Freiling87** [Abbysssal/RogueLibs#44]
### Describe the problem

Accessing in-game display name from TraitInfo class is relatively complicated. 

### Describe the solution

Considering the game's code uses string comparisons so frequently, I'd find it useful if that field were exposed.

**Comment by Abbysssal** [comment]
eb97e1542bbe3a76b861923099ef8a44a311173a resolves this issue.
```cs
TraitInfo info = TraitInfo.Get(typeof(MyTrait));
CustomName name = info.GetName();
string text = name.GetCurrent();
```
